#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# run_pipeline.sh — Single-command, fully automated loop-transform
#                   visualization pipeline.
#
# Usage:
#   ./run_pipeline.sh input.c loop-unroll
#   ./run_pipeline.sh input.c licm
#   ./run_pipeline.sh input.c "loop-unroll,licm"
#   ./run_pipeline.sh input.c loop-vectorize --port 9000
#   ./run_pipeline.sh input.c loop-interchange --no-serve
#   ./run_pipeline.sh testcases/gpu_reduction.c loop-unroll --gpu gfx90a
#
# What it does (zero manual/AI steps):
#   1. Compiles C/C++ → LLVM IR
#      • Host (default): -O0 + opt prep (mem2reg, …) → before.ll
#      • GPU (--gpu MCPU): clang -target amdgcn-amd-amdhsa -mcpu=MCPU
#        -O1 -fno-unroll-loops → before.ll (AMDGPU stack in addrspace(5)
#        often blocks mem2reg at -O0; this path is script-driven, not “AI”.)
#   2. Applies opt -passes=<PASS> → transformed IR
#   3. Runs ll-dump on both → CFG + loop + memory JSON
#   4. Runs perf stat or rocprof → perf_compare.json
#   5. Serves visualization on http://localhost:<PORT>/
#
# All artifacts are generated by the tool's own code:
#   ll-dump (C++ binary)  → before.json, after.json
#   perf stat / rocprof   → perf_compare.json
#   opt (LLVM)            → remarks.json (optional)
#
# Environment overrides:
#   CLANG        — path to clang       (auto-detected from LLVM build or PATH)
#   OPT          — path to opt         (auto-detected from LLVM build or PATH)
#   LLVM_CONFIG  — path to llvm-config (for building ll-dump)
#   PREP_PASSES  — SSA prep passes     (default: mem2reg,lcssa,loop-simplify)
#   PORT         — HTTP server port    (default: 8765)
#   PROFILER     — force perf or rocprof
#   GPU_ARCH     — GPU target (e.g. gfx90a) — forces rocprof
#   GPU_MCPU     — if set (or use --gpu MCPU), AMDGPU kernel compile path above
#   CLANG_GPU_TRIPLE — default amdgcn-amd-amdhsa
#   PERF_RUNS    — number of perf stat iterations (default: 5)
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

# ---- Parse arguments ----
SOURCE=""
PASS=""
SERVE=1
USER_PORT=""
GPU_MCPU="${GPU_MCPU:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)    USER_PORT="$2"; shift 2 ;;
    --no-serve) SERVE=0; shift ;;
    --gpu)     GPU_MCPU="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 <source.c> <pass-name> [--gpu MCPU] [--port N] [--no-serve]"
      echo ""
      echo "Examples:"
      echo "  $0 test.c loop-unroll"
      echo "  $0 test.c licm --port 9000"
      echo "  $0 test.c \"loop-unroll,loop-vectorize\" --no-serve"
      echo "  $0 testcases/gpu_reduction.c loop-unroll --gpu gfx90a"
      echo ""
      echo "GPU: use --gpu gfx90a (or set GPU_MCPU=gfx90a). Compiles AMDGPU IR with"
      echo "     -O1 -fno-unroll-loops as before.ll, then runs opt with your pass."
      echo "     Same clang/opt as manual commands — encoded here so nothing is ad hoc."
      exit 0 ;;
    *)
      if [ -z "$SOURCE" ]; then
        SOURCE="$1"
      elif [ -z "$PASS" ]; then
        PASS="$1"
      else
        echo "ERROR: unexpected argument '$1'" >&2; exit 1
      fi
      shift ;;
  esac
done

[ -z "$SOURCE" ] && { echo "ERROR: missing source file. Run $0 --help"; exit 1; }
[ -z "$PASS" ]   && { echo "ERROR: missing pass name. Run $0 --help"; exit 1; }
[ ! -f "$SOURCE" ] && { echo "ERROR: file not found: $SOURCE"; exit 1; }

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT_DIR="$ROOT_DIR/scripts"
WEBDIR="$ROOT_DIR/web"

[ -n "$USER_PORT" ] && export PORT="$USER_PORT"

# ---- Auto-detect CLANG / OPT from sibling LLVM build ----
auto_detect_tools() {
  if [ -z "${CLANG:-}" ] || [ -z "${OPT:-}" ]; then
    local llvm_build=""
    for candidate in \
      "$ROOT_DIR/../llvm-project/build/bin" \
      "$ROOT_DIR/../llvm-project/build-release/bin" \
      "$(dirname "$(command -v clang 2>/dev/null || true)" 2>/dev/null)"; do
      if [ -x "${candidate}/clang" ] && [ -x "${candidate}/opt" ]; then
        llvm_build="$candidate"
        break
      fi
    done
    if [ -n "$llvm_build" ]; then
      export CLANG="${CLANG:-$llvm_build/clang}"
      export OPT="${OPT:-$llvm_build/opt}"
      export LLVM_CONFIG="${LLVM_CONFIG:-$llvm_build/llvm-config}"
    fi
  fi
  export CLANG="${CLANG:-clang}"
  export OPT="${OPT:-opt}"
}

auto_detect_tools

CLANG_GPU_TRIPLE="${CLANG_GPU_TRIPLE:-amdgcn-amd-amdhsa}"

# ---- Ensure ll-dump is built ----
if [ ! -f "$ROOT_DIR/ll-dump" ]; then
  echo "==> Building ll-dump..."
  make -C "$ROOT_DIR" -j"$(nproc)" 2>/dev/null || make -C "$ROOT_DIR"
fi

echo "╔══════════════════════════════════════════════════╗"
echo "║   LLVM Loop-Transform Visualiser — Pipeline     ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  Source : $SOURCE"
echo "║  Pass   : $PASS"
if [ -n "$GPU_MCPU" ]; then
  echo "║  GPU    : $CLANG_GPU_TRIPLE  mcpu=$GPU_MCPU  (automated AMDGPU path)"
fi
echo "║  Clang  : $($CLANG --version 2>&1 | head -1)"
echo "║  Opt    : $($OPT --version 2>&1 | head -1)"
echo "╚══════════════════════════════════════════════════╝"
echo ""

PREP_PASSES="${PREP_PASSES:-mem2reg,lcssa,loop-simplify}"

TMPDIR_PIPE=$(mktemp -d)
trap "rm -rf $TMPDIR_PIPE" EXIT

BEFORE_LL="$TMPDIR_PIPE/before.ll"
AFTER_LL="$TMPDIR_PIPE/after.ll"
RAW_LL="$TMPDIR_PIPE/raw.ll"

if [ -n "$GPU_MCPU" ]; then
  # AMDGPU kernels: -O0 + mem2reg often leaves stack traffic in addrspace(5) and
  # loop passes may no-op. This path matches a standard “before unroll” baseline.
  echo "==> [1–2/5] GPU kernel: clang → before.ll ($CLANG_GPU_TRIPLE, -mcpu=$GPU_MCPU, -O1 -fno-unroll-loops)..."
  "$CLANG" -target "$CLANG_GPU_TRIPLE" -mcpu="$GPU_MCPU" \
    -O1 -fno-unroll-loops -emit-llvm -S "$SOURCE" -o "$BEFORE_LL"
else
  # ---- Step 1: Compile C/C++ → unoptimized IR (no optnone) ----
  echo "==> [1/5] Compiling $SOURCE → raw LLVM IR..."
  "$CLANG" -O0 -Xclang -disable-O0-optnone -emit-llvm -S "$SOURCE" -o "$RAW_LL"

  # ---- Step 2: Prep passes → clean SSA (before.ll) ----
  echo "==> [2/5] Applying prep passes ($PREP_PASSES) → before.ll..."
  "$OPT" -passes="$PREP_PASSES" "$RAW_LL" -S -o "$BEFORE_LL"
fi

BEFORE_LINES=$(wc -l < "$BEFORE_LL")
echo "    before.ll: $BEFORE_LINES lines"

# ---- Step 3: Target pass → after.ll ----
echo "==> [3/5] Applying opt -passes=$PASS → after.ll..."
"$OPT" -passes="$PASS" "$BEFORE_LL" -S -o "$AFTER_LL" 2>&1 || {
  echo "ERROR: opt -passes=$PASS failed."
  echo "  Common loop passes: loop-unroll, loop-distribute, licm,"
  echo "  loop-interchange, loop-vectorize, loop-sink, loop-unroll-and-jam,"
  echo "  loop-versioning-licm, simple-loop-unswitch"
  exit 1
}

AFTER_LINES=$(wc -l < "$AFTER_LL")
echo "    after.ll:  $AFTER_LINES lines"

if diff -q "$BEFORE_LL" "$AFTER_LL" >/dev/null 2>&1; then
  echo ""
  echo "NOTE: Pass '$PASS' had no effect on this input."
  echo "      The visualization will show identical before/after."
fi

DIFF_LINES=$( (diff "$BEFORE_LL" "$AFTER_LL" || true) | wc -l )
echo "    diff: $DIFF_LINES lines changed"

# ---- Step 4: ll-dump → JSON ----
echo "==> [4/5] Extracting CFG + loop features (ll-dump)..."
"$ROOT_DIR/ll-dump" "$BEFORE_LL" -o "$WEBDIR/before.json"
"$ROOT_DIR/ll-dump" "$AFTER_LL"  -o "$WEBDIR/after.json"

# ---- Step 5: Perf profiling ----
is_gpu_ir() {
  grep -qE 'triple\s*=\s*"(amdgcn|nvptx|spir)' "$1" 2>/dev/null
}

choose_profiler() {
  if [ -n "${PROFILER:-}" ]; then echo "$PROFILER"; return; fi
  if [ -n "${GPU_ARCH:-}" ]; then echo "rocprof"; return; fi
  if is_gpu_ir "$BEFORE_LL" || is_gpu_ir "$AFTER_LL"; then echo "rocprof"; return; fi
  echo "perf"
}

PROF=$(choose_profiler)
echo "==> [5/5] Performance profiling ($PROF)..."

if [ "$PROF" = "rocprof" ]; then
  if command -v rocprof &>/dev/null; then
    if ! "$SCRIPT_DIR/run-rocprof.sh" "$BEFORE_LL" "$AFTER_LL" "$WEBDIR"; then
      echo "    rocprof / link step failed (common for bare device IR) — IR + JSON still valid; open the UI for structural analysis."
    fi
  else
    echo "    rocprof not found — skipping GPU profiling."
  fi
else
  if command -v perf &>/dev/null; then
    "$SCRIPT_DIR/run-perf.sh" "$BEFORE_LL" "$AFTER_LL" "$WEBDIR" || \
      echo "    perf run failed — continuing without perf_compare.json."
  else
    echo "    perf not available — skipping CPU profiling."
    echo "    Install linux-tools-$(uname -r) for hardware counter data."
  fi
fi

# ---- Optional: optimization remarks ----
if [ -n "${OPT_PASS:-}" ] || true; then
  OPT_PASS_NAME="${PASS%%,*}"
  "$OPT" -passes="$PASS" \
    -pass-remarks="$OPT_PASS_NAME" \
    -pass-remarks-missed="$OPT_PASS_NAME" \
    -pass-remarks-analysis="$OPT_PASS_NAME" \
    -pass-remarks-output="$WEBDIR/remarks.yaml" \
    "$BEFORE_LL" -S -o /dev/null 2>/dev/null || true
  if [ -f "$WEBDIR/remarks.yaml" ]; then
    python3 "$SCRIPT_DIR/parse-remarks.py" "$WEBDIR/remarks.yaml" "$WEBDIR/remarks.json" 2>/dev/null && \
      echo "    Wrote remarks.json" || true
  fi
fi

# ---- Copy .ll to web for reference download ----
cp "$BEFORE_LL" "$WEBDIR/before.ll" 2>/dev/null || true
cp "$AFTER_LL"  "$WEBDIR/after.ll"  2>/dev/null || true

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  Artifacts generated (all by tool scripts):     ║"
echo "║    web/before.json       ← ll-dump              ║"
echo "║    web/after.json        ← ll-dump              ║"
echo "║    web/perf_compare.json ← perf stat / rocprof  ║"
echo "║    web/before.ll         ← clang + opt          ║"
echo "║    web/after.ll          ← clang + opt          ║"
echo "╚══════════════════════════════════════════════════╝"

if [ "$SERVE" -eq 0 ]; then
  echo ""
  echo "Pipeline complete (--no-serve). Serve manually with:"
  echo "  cd $WEBDIR && python3 -m http.server ${PORT:-8765}"
  exit 0
fi

# ---- Find free port and serve ----
find_free_port() {
  local p="$1" max=$(( $1 + 20 ))
  while [ "$p" -le "$max" ]; do
    if ! python3 -c "import socket; s=socket.socket(); s.settimeout(0.1); s.connect(('127.0.0.1',$p))" 2>/dev/null; then
      echo "$p"; return
    fi
    p=$(( p + 1 ))
  done
  echo "$1"
}

PORT=$(find_free_port "${PORT:-8765}")

echo ""
echo "  Serving: http://localhost:$PORT/"
echo "  Select 'Latest analysis' in the dropdown."
echo ""

cd "$WEBDIR" && python3 -m http.server "$PORT"
